using MasterZoneMvc.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;

namespace MasterZoneMvc.Common.Seed
{
    public class PermissionSeed
    {
        private MasterZoneMvc.DAL.MasterZoneDbContext context;

        public PermissionSeed(MasterZoneMvc.DAL.MasterZoneDbContext _context)
        {
            context = _context;
        }

        public void SeedData()
        {
            // Business Panel Permissions [Panel Links]
            context.Permissions.AddOrUpdate(x => x.Id,
                new Permission() { Id = 1, KeyName = "Dashboard", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Dashboard"},
                new Permission() { Id = 2, KeyName = "ManageStaff", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Staff"},
                new Permission() { Id = 3, KeyName = "ManageStaff_ViewStaff", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 2, TextValue = "View Staff"},
                new Permission() { Id = 4, KeyName = "ManageStaff_StaffSalary", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 2, TextValue = "Manage Salary"},
                new Permission() { Id = 5, KeyName = "ManageBusinessPlans", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Plans/Packages"},
                new Permission() { Id = 6, KeyName = "ManageScheduleClass", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "My Schedule/Classes" },
                new Permission() { Id = 7, KeyName = "ManageCertifications", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Certifications" },
                new Permission() { Id = 8, KeyName = "ManageGroups", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Groups" },
                new Permission() { Id = 9, KeyName = "ManageEvents", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Events" },
                new Permission() { Id = 10, KeyName = "ManageDiscounts", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Discounts" },
                new Permission() { Id = 11, KeyName = "ManageAdvertisements", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Advertisements" },
                new Permission() { Id = 12, KeyName = "ManageExams", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Exams" },
                new Permission() { Id = 13, KeyName = "ManagePayments", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Payments" },
                new Permission() { Id = 14, KeyName = "ManageStudent", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Student" },
                new Permission() { Id = 15, KeyName = "Miscellaneous", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Miscellaneous" },
                new Permission() { Id = 16, KeyName = "ManageEnquiries", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Enquiries" },
                new Permission() { Id = 17, KeyName = "MyAccount", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "My Account" },
                new Permission() { Id = 18, KeyName = "Backup", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Backup" },
                new Permission() { Id = 19, KeyName = "ManageStaff_StaffAttendance", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 2, TextValue = "Attendance" },
                new Permission() { Id = 20, KeyName = "ManageCertifications_VerifyCertificates", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 7, TextValue = "Certificates Verify" },
                new Permission() { Id = 21, KeyName = "Miscellaneous_ViewMessages", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 15, TextValue = "View Messages" },
                new Permission() { Id = 22, KeyName = "Miscellaneous_Notifications", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 15, TextValue = "Notifications" },
                new Permission() { Id = 23, KeyName = "Miscellaneous_BusinessTiming", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 15, TextValue = "Time Slots" },
                new Permission() { Id = 24, KeyName = "ManageBusinessPlans_ViewPackages", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 5, TextValue = "View Packages" },
                new Permission() { Id = 25, KeyName = "ManageBusinessPlans_TransferPackage", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 5, TextValue = "Transfer Package" },
                new Permission() { Id = 26, KeyName = "ManageQueries", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Queries" },
                new Permission() { Id = 27, KeyName = "ManageStudent_ViewStudent", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 14, TextValue = "View Student" },
                new Permission() { Id = 28, KeyName = "ManageStudent_ViewStudentClass", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 14, TextValue = "View Student Class" },
                new Permission() { Id = 29, KeyName = "Miscellaneous_ManageReviews", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 15, TextValue = "Manage Reviews" },
                new Permission() { Id = 30, KeyName = "ManageStaff_ViewStaff_AddStaff", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 3, TextValue = "Add Staff" },
                new Permission() { Id = 31, KeyName = "ManageStaff_ViewStaff_EditStaff", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 3, TextValue = "Edit Staff" },
                new Permission() { Id = 32, KeyName = "ManageStaff_ViewStaff_Delete", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 3, TextValue = "Delete Staff" },
                new Permission() { Id = 33, KeyName = "ManageStaff_StaffSalary_AddSalary", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 4, TextValue = "Add Salary" },
                new Permission() { Id = 34, KeyName = "ManageStaff_StaffSalary_EditSalary", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 4, TextValue = "Edit Salary" },
                new Permission() { Id = 35, KeyName = "ManageStaff_StaffSalary_DeleteSalary", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 4, TextValue = "Delete Salary" },
                new Permission() { Id = 36, KeyName = "ManageStaff_StaffAttendance_AddStaffAttendance", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 19, TextValue = "Add Attendance" },
                new Permission() { Id = 37, KeyName = "ManageBusinessPlans_ViewPackages_AddPackages", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 24, TextValue = "Add Packages" },
                new Permission() { Id = 38, KeyName = "ManageBusinessPlans_ViewPackages_EditPackages", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 24, TextValue = "Edit Packages" },
                new Permission() { Id = 39, KeyName = "ManageBusinessPlans_ViewPackages_DeletePackages", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 24, TextValue = "Delete Packages" },
                new Permission() { Id = 40, KeyName = "ManageBusinessPlans_ViewTrainings", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 5, TextValue = "View Trainings" },
                new Permission() { Id = 41, KeyName = "ManageBusinessPlans_ViewTrainings_AddTrainings", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 40, TextValue = "Add Trainings" },
                new Permission() { Id = 42, KeyName = "ManageBusinessPlans_ViewTrainings_EditTrainings", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 40, TextValue = "Edit Trainings" },
                new Permission() { Id = 43, KeyName = "ManageBusinessPlans_ViewTrainings_DeleteTrainings", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 40, TextValue = "Delete Trainings" },
                new Permission() { Id = 44, KeyName = "ManageScheduleClass_AddScheduleClass", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 6, TextValue = "Add Schedule/Classes" },
                new Permission() { Id = 45, KeyName = "ManageScheduleClass_EditScheduleClass", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 6, TextValue = "Edit Schedule/Classes" },
                new Permission() { Id = 46, KeyName = "ManageScheduleClass_DeleteScheduleClass", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 6, TextValue = "Delete Schedule/Classes" },
                new Permission() { Id = 47, KeyName = "ManageGroups_AddGroups", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 8, TextValue = "Add Groups" },
                new Permission() { Id = 48, KeyName = "ManageGroups_EditGroups", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 8, TextValue = "Edit Groups" },
                new Permission() { Id = 49, KeyName = "ManageGroups_DeleteGroups", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 8, TextValue = "Delete Groups" },
                new Permission() { Id = 50, KeyName = "ManageGroups_AddGroupMember", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 8, TextValue = "Add GroupMembers" },
                new Permission() { Id = 51, KeyName = "ManageEvents_AddEvents", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 9, TextValue = "Add Events" },
                new Permission() { Id = 52, KeyName = "ManageEvents_EditEvents", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 9, TextValue = "Edit Events" },
                new Permission() { Id = 53, KeyName = "ManageEvents_DeleteEvents", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 9, TextValue = "Delete Events" },
                new Permission() { Id = 54, KeyName = "ManageDiscounts_AddDiscounts", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 10, TextValue = "Add Discounts" },
                new Permission() { Id = 55, KeyName = "ManageDiscounts_EditDiscounts", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 10, TextValue = "Edit Discounts" },
                new Permission() { Id = 56, KeyName = "ManageDiscounts_DeleteDiscounts", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 10, TextValue = "Delete Discounts" },
                new Permission() { Id = 57, KeyName = "ManageGroups_ViewGroupMembers", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 8, TextValue = "View GroupMembers" },
                new Permission() { Id = 58, KeyName = "ManageGroups_DeleteGroupMember", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 8, TextValue = "Delete GroupMembers" },
                new Permission() { Id = 59, KeyName = "ManageDiscounts_ViewDetailsDiscounts", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 10, TextValue = "View Details Discounts" },
                new Permission() { Id = 60, KeyName = "ManageAdvertisements_AddAdvertisements", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 11, TextValue = "Add Advertisements" },
                new Permission() { Id = 61, KeyName = "ManageAdvertisements_DeleteAdvertisements", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 11, TextValue = "Delete Advertisements" },
                new Permission() { Id = 62, KeyName = "ManageAdvertisements_ChangeStatusAdvertisements", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 11, TextValue = "Change Status Advertisements" },
                new Permission() { Id = 63, KeyName = "ManageExams_AddExam", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 12, TextValue = "Add Exams" },
                new Permission() { Id = 64, KeyName = "ManageExams_EditExam", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 12, TextValue = "Edit Exams" },
                new Permission() { Id = 65, KeyName = "ManageExams_DeleteExam", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 12, TextValue = "Delete Exams" },
                new Permission() { Id = 66, KeyName = "ManagePayments_ExportPayments", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 13, TextValue = "Export Payments" },
                new Permission() { Id = 67, KeyName = "ManageStudent_ViewStudent_ChangeStatusStudents", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 27, TextValue = "Change Status Student" },
                new Permission() { Id = 68, KeyName = "Miscellaneous_ManageReviews_ChangeStatusReviews", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 29, TextValue = "Chnage Status Reviews" },
                new Permission() { Id = 69, KeyName = "Miscellaneous_ManageReviews_ViewReviews", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 29, TextValue = "View Reviews" },
                new Permission() { Id = 70, KeyName = "Miscellaneous_ManageReviews_EditReviews", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 29, TextValue = "Edit Reviews" },
                new Permission() { Id = 71, KeyName = "Miscellaneous_ManageReviews_DeleteReviews", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 29, TextValue = "Delete Reviews" },
                new Permission() { Id = 72, KeyName = "Miscellaneous_ManageBusinessVideos", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 15, TextValue = " Manage Business Videos" },
                new Permission() { Id = 73, KeyName = "Miscellaneous_ManageBusinessVideos_ViewVideos", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 72, TextValue = "View Videos" },
                new Permission() { Id = 74, KeyName = "Miscellaneous_ManageBusinessVideos_AddVideos", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 72, TextValue = "Add Videos" },
                new Permission() { Id = 75, KeyName = "Miscellaneous_ManageBusinessVideos_DeleteVideos", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 72, TextValue = "Delete Videos" },
                new Permission() { Id = 76, KeyName = "Miscellaneous_ManageBusinessImages", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 15, TextValue = " Manage Business Images" },
                new Permission() { Id = 77, KeyName = "Miscellaneous_ManageBusinessImages_ViewImages", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 76, TextValue = "View Business Images" },
                new Permission() { Id = 78, KeyName = "Miscellaneous_ManageBusinessImages_AddImages", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 76, TextValue = "Add Business Images" },
                new Permission() { Id = 79, KeyName = "Miscellaneous_ManageBusinessImages_DeleteImages", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 76, TextValue = "Delete Business Images" },
                new Permission() { Id = 80, KeyName = "ManageQueries_ViewQueries", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 26, TextValue = "View Queries" },
                new Permission() { Id = 81, KeyName = "ManageQueries_ReplyQueries", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 26, TextValue = "Reply Queries" },
                new Permission() { Id = 82, KeyName = "ManageEnquiries", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Enquiries" },
                new Permission() { Id = 83, KeyName = "ManageEnquiries_ViewEnquiries", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 82, TextValue = "View Enquiries" },
                new Permission() { Id = 84, KeyName = "ManageEnquiries_ViewEnquiries_AddEnquiries", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 82, TextValue = "Add Enquiries" },
                new Permission() { Id = 85, KeyName = "ManageEnquiries_ViewEnquiries_EditEnquiries", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 82, TextValue = "Edit Enquiries" },
                new Permission() { Id = 86, KeyName = "ManageEnquiries_ViewEnquiries_DeleteEnquiries", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 82, TextValue = "Delete Enquiries" },
                new Permission() { Id = 87, KeyName = "ManageAccount", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Account" },
                new Permission() { Id = 88, KeyName = "MyAccount_ViewAccount", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 17, TextValue = "View Account" },
                new Permission() { Id = 89, KeyName = "MyAccount_UpdateAccount", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 17, TextValue = "Update Account" },
                new Permission() { Id = 90, KeyName = "ManageStaff_ViewStaff_ChangeStatus", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 3, TextValue = "Change Status Staff" },
                new Permission() { Id = 91, KeyName = "ManageScheduleClass_ViewScheduleClass", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 6, TextValue = "View Schedule/Classes" },
                new Permission() { Id = 92, KeyName = "ManageGroups_ViewGroups", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 8, TextValue = "View Groups" },
                new Permission() { Id = 93, KeyName = "ManageEvents_ViewEvents", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 9, TextValue = "View Events" },
                new Permission() { Id = 94, KeyName = "ManageDiscounts_ViewDiscounts", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 10, TextValue = "View Discounts" },
                new Permission() { Id = 95, KeyName = "ManageAdvertisements_ViewAdvertisements", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 11, TextValue = "View Advertisements" },
                new Permission() { Id = 96, KeyName = "ManageExams_ViewExam", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 12, TextValue = "View Exams" },
                new Permission() { Id = 97, KeyName = "ManagePayments_ViewPayments", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 13, TextValue = "View Payments" },
                new Permission() { Id = 98, KeyName = "ManageBusiness", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Business" },
                new Permission() { Id = 99, KeyName = "ManageUserAccount", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage User Account" },
                new Permission() { Id = 100, KeyName = "PaymentTransactions", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Payment/Transactions" },
                new Permission() { Id = 101, KeyName = "ManageCertificate", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Certificate" },
                new Permission() { Id = 102, KeyName = "ManageAdvertisement", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Advertisement" },
                new Permission() { Id = 103, KeyName = "ManageCategories", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Categories" },
                new Permission() { Id = 104, KeyName = "ManageMenu", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Menu" },
                new Permission() { Id = 105, KeyName = "AccountSettings", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Account Settings" },
                new Permission() { Id = 106, KeyName = "Plans_Package", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = " Plans/Package" },
                new Permission() { Id = 107, KeyName = "Backup", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Backup" },
                new Permission() { Id = 108, KeyName = "ManageExamsForm_ChangeStatus", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 12, TextValue = "Change Exam Form Status" },
                new Permission() { Id = 109, KeyName = "ManageExamsForm_ViewSubmitExamForm", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 12, TextValue = "View Submit Exam Form Data" },

                new Permission() { Id = 110, KeyName = "ManageSubmitExamsForm", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage the submit exam form" },
                new Permission() { Id = 111, KeyName = "ManageSubmitExamsForm_ViewDetailExamForm", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 110, TextValue = "View the detail of submitted Exam Form Data" },
                new Permission() { Id = 112, KeyName = "ManageSubmitExamsForm_PrintAdmitCard", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 110, TextValue = "Print the candidate admit card" },
                new Permission() { Id = 113, KeyName = "Miscellaneous_ProfilePage", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 15, TextValue = "Profile Page" },
                new Permission() { Id = 114, KeyName = "Miscellaneous_BusinessSponsor", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 15, TextValue = "Business Sponsors" },
                new Permission() { Id = 115, KeyName = "Miscellaneous_ManageBusinessService", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 15, TextValue = "Manage Service" },
                new Permission() { Id = 116, KeyName = "ManageBranches", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Manage Branches" },
                new Permission() { Id = 117, KeyName = "ManageBranches_EditBranch", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 116, TextValue = "Edit Branch" },
                new Permission() { Id = 118, KeyName = "ManageBranches_DeleteBranch", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 116, TextValue = "Delete Branch" },
                new Permission() { Id = 119, KeyName = "ManageBranches_ViewStudentsBranchDetail", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 116, TextValue = "View Students Branch Detail" },
                new Permission() { Id = 120, KeyName = "ManageBranches_ViewEventsBranch", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 116, TextValue = "View Events Branch Detail" },
                new Permission() { Id = 121, KeyName = "ManageBranches_ViewTansactionsBranch", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 116, TextValue = "View Transactions Branches Detail" },
                new Permission() { Id = 122, KeyName = "ManageBranches_ViewStaffBranch", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 116, TextValue = "View Staffs Branches Detail" },
                new Permission() { Id = 123, KeyName = "ManageAllClasses", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Classes" },
                new Permission() { Id = 124, KeyName = "ManageAllTrainings", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Trainings" },
                new Permission() { Id = 125, KeyName = "ManageAllEvents", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Events" },
                new Permission() { Id = 126, KeyName = "ManageAllInstructors", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Instructors" },
                new Permission() { Id = 127, KeyName = "CustomForm", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "CustomForm" },
                new Permission() { Id = 128, KeyName = "ViewCustomForm", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 127, TextValue = "View CustomForm" },
                new Permission() { Id = 129, KeyName = "BusinessTransferForm", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 127, TextValue = "Business TransferForm" },
                new Permission() { Id = 130, KeyName = "ManageEventCategory", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Event Category" },
                new Permission() { Id = 131, KeyName = "ManageStaffCategory", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Staff Category" },
                new Permission() { Id = 132, KeyName = "ScheduleCourses", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "ScheduleCourses" },
                new Permission() { Id = 133, KeyName = "MyBooking", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "MyBooking" },
                new Permission() { Id = 134, KeyName = "ManageEventCategory", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Event Category" },
                new Permission() { Id = 135, KeyName = "ManageStaffCategory", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage Staff Category" },
                new Permission() { Id = 136, KeyName = "MyBooking", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage My Booking" },
                new Permission() { Id = 137, KeyName = "MyCourses", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage My Courses" },
                new Permission() { Id = 138, KeyName = "ScheduleCourses", Comments = "", PanelTypeId = StaticResources.PanelType_SuperAdmin, ParentPermissionId = 0, TextValue = "Manage My Course" },
                new Permission() { Id = 139, KeyName = "Enquiry", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Enquiry" },
                new Permission() { Id = 140, KeyName = "sports", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "Sports" },
                new Permission() { Id = 141, KeyName = "sportBooking", Comments = "", PanelTypeId = StaticResources.PanelType_Business, ParentPermissionId = 0, TextValue = "sportsBooking" }
                );
        }
    }
}
