//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, same email is already exist/used by other user!.
        /// </summary>
        internal static string AlreadyEmailExit_ErrorMessage {
            get {
                return ResourceManager.GetString("AlreadyEmailExit_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount cannot be zero!.
        /// </summary>
        internal static string AmountCannotBeZero {
            get {
                return ResourceManager.GetString("AmountCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated!.
        /// </summary>
        internal static string Authenticated {
            get {
                return ResourceManager.GetString("Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization has been denied for this request!.
        /// </summary>
        internal static string AuthorizationErrorMessage {
            get {
                return ResourceManager.GetString("AuthorizationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category not exists!.
        /// </summary>
        internal static string BusinessCategoryNot_Exists {
            get {
                return ResourceManager.GetString("BusinessCategoryNot_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Business Owner donesnot exist by  user!.
        /// </summary>
        internal static string BusinessOwnerNotExist_ErrorMessage {
            get {
                return ResourceManager.GetString("BusinessOwnerNotExist_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number must be of 16 digits.
        /// </summary>
        internal static string CardNumberMustBeOf16Digit {
            get {
                return ResourceManager.GetString("CardNumberMustBeOf16Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found!.
        /// </summary>
        internal static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Already Purchased!.
        /// </summary>
        internal static string ClassAlreadyPurchased {
            get {
                return ResourceManager.GetString("ClassAlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class only available on Days- {0}.
        /// </summary>
        internal static string ClassAvailabilityDays {
            get {
                return ResourceManager.GetString("ClassAvailabilityDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch is already full! Cannot book!.
        /// </summary>
        internal static string ClassBatchFull_ErrorMessage {
            get {
                return ResourceManager.GetString("ClassBatchFull_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch not found!.
        /// </summary>
        internal static string ClassBatchNotFound_ErrorMessage {
            get {
                return ResourceManager.GetString("ClassBatchNotFound_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class  not found!.
        /// </summary>
        internal static string ClassNotFound {
            get {
                return ResourceManager.GetString("ClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course is already Purchased!.
        /// </summary>
        internal static string CourseAlreadyPurchased {
            get {
                return ResourceManager.GetString("CourseAlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Not Found!.
        /// </summary>
        internal static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while updating data. Transaction failed!.
        /// </summary>
        internal static string DatabaseTransactionFailedErrorMessage {
            get {
                return ResourceManager.GetString("DatabaseTransactionFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already Confirmed!.
        /// </summary>
        internal static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Already Purchased!.
        /// </summary>
        internal static string EventAlreadyPurchased {
            get {
                return ResourceManager.GetString("EventAlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found!.
        /// </summary>
        internal static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size too large. Please select a smaller image. (upto 5 MB).
        /// </summary>
        internal static string ImageSizeMessage {
            get {
                return ResourceManager.GetString("ImageSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image type. Please select a JPEG, PNG.
        /// </summary>
        internal static string InvaildImageMessage {
            get {
                return ResourceManager.GetString("InvaildImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request data!.
        /// </summary>
        internal static string InvaildRequestDataPassed {
            get {
                return ResourceManager.GetString("InvaildRequestDataPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        internal static string InvaildRequestMessage {
            get {
                return ResourceManager.GetString("InvaildRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Category!.
        /// </summary>
        internal static string InvalidBusinessCategory {
            get {
                return ResourceManager.GetString("InvalidBusinessCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data!.
        /// </summary>
        internal static string InvalidData_ErrorMessage {
            get {
                return ResourceManager.GetString("InvalidData_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id.
        /// </summary>
        internal static string InvalidIdErrorMessage {
            get {
                return ResourceManager.GetString("InvalidIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Link!.
        /// </summary>
        internal static string InvalidLink {
            get {
                return ResourceManager.GetString("InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Master Id!.
        /// </summary>
        internal static string InvalidMasterId {
            get {
                return ResourceManager.GetString("InvalidMasterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mode.
        /// </summary>
        internal static string InvalidMode {
            get {
                return ResourceManager.GetString("InvalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not available for booking!.
        /// </summary>
        internal static string ItemNotAvailableForBooking {
            get {
                return ResourceManager.GetString("ItemNotAvailableForBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join date not vaild.
        /// </summary>
        internal static string JoinDateNotValid {
            get {
                return ResourceManager.GetString("JoinDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License not found!.
        /// </summary>
        internal static string LicenseNotFound {
            get {
                return ResourceManager.GetString("LicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link has been expired!.
        /// </summary>
        internal static string LinkHasbeenExpired {
            get {
                return ResourceManager.GetString("LinkHasbeenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Id Required!.
        /// </summary>
        internal static string Login_MasterIdRequired {
            get {
                return ResourceManager.GetString("Login_MasterIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search box can&apos;t be empty !.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found!.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numeric value!.
        /// </summary>
        internal static string OnlyNumericValuesAllowed_ErrorMessage {
            get {
                return ResourceManager.GetString("OnlyNumericValuesAllowed_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select only .PNG image..
        /// </summary>
        internal static string OnlyPNGImageValid_ErrorMessage {
            get {
                return ResourceManager.GetString("OnlyPNGImageValid_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only user Master-Id is allowed &apos;MU_0000&apos;.
        /// </summary>
        internal static string OnlyUserMasterIdIsAllowed {
            get {
                return ResourceManager.GetString("OnlyUserMasterIdIsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid amount is not equal to the total amount.
        /// </summary>
        internal static string PaidAmountNotEqualsToTotalAmount {
            get {
                return ResourceManager.GetString("PaidAmountNotEqualsToTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause dates conflict with existing class booking.
        /// </summary>
        internal static string PauseClassConflict_Error {
            get {
                return ResourceManager.GetString("PauseClassConflict_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan already purchased!.
        /// </summary>
        internal static string PlanAlreadyPurchased {
            get {
                return ResourceManager.GetString("PlanAlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Not Found!.
        /// </summary>
        internal static string PlanNotFound {
            get {
                return ResourceManager.GetString("PlanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some technical error, please try again!.
        /// </summary>
        internal static string TechincalErrorMessage {
            get {
                return ResourceManager.GetString("TechincalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training already purchased!.
        /// </summary>
        internal static string TrainingAlreadyPurchased {
            get {
                return ResourceManager.GetString("TrainingAlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Not Found!.
        /// </summary>
        internal static string TrainingNotFound {
            get {
                return ResourceManager.GetString("TrainingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized! Invalid Token!.
        /// </summary>
        internal static string UnAuthorizedErrorMessage {
            get {
                return ResourceManager.GetString("UnAuthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data!.
        /// </summary>
        internal static string ValidInformationMessage {
            get {
                return ResourceManager.GetString("ValidInformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
