//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NotificationMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Class has been booked by {1} on {2} IST.
        /// </summary>
        internal static string BusinessNotification_NewClassBookingMessage {
            get {
                return ResourceManager.GetString("BusinessNotification_NewClassBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Class Booking - {0}.
        /// </summary>
        internal static string BusinessNotification_NewClassBookingTitle {
            get {
                return ResourceManager.GetString("BusinessNotification_NewClassBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Course has been booked by {1} !.
        /// </summary>
        internal static string BusinessNotification_NewCourseBookingMessage {
            get {
                return ResourceManager.GetString("BusinessNotification_NewCourseBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Course Booking - {0}.
        /// </summary>
        internal static string BusinessNotification_NewCourseBookingTitle {
            get {
                return ResourceManager.GetString("BusinessNotification_NewCourseBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Event has been booked by {1} on {2} IST.
        /// </summary>
        internal static string BusinessNotification_NewEventBookingMessage {
            get {
                return ResourceManager.GetString("BusinessNotification_NewEventBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event Booking - {0}.
        /// </summary>
        internal static string BusinessNotification_NewEventBookingTitle {
            get {
                return ResourceManager.GetString("BusinessNotification_NewEventBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Plan has been booked by {1} on {2} IST.
        /// </summary>
        internal static string BusinessNotification_NewPlanBookingMessage {
            get {
                return ResourceManager.GetString("BusinessNotification_NewPlanBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Plan Booking - {0}.
        /// </summary>
        internal static string BusinessNotification_NewPlanBookingTitle {
            get {
                return ResourceManager.GetString("BusinessNotification_NewPlanBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Training has been booked by {1} on {2} IST.
        /// </summary>
        internal static string BusinessNotification_NewTrainingBookingMessage {
            get {
                return ResourceManager.GetString("BusinessNotification_NewTrainingBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Training Booking - {0}.
        /// </summary>
        internal static string BusinessNotification_NewTrainingBookingTitle {
            get {
                return ResourceManager.GetString("BusinessNotification_NewTrainingBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Class has been booked on {1} IST.
        /// </summary>
        internal static string UserNotification_NewClassBookingMessage {
            get {
                return ResourceManager.GetString("UserNotification_NewClassBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked Class - {0}.
        /// </summary>
        internal static string UserNotification_NewClassBookingTitle {
            get {
                return ResourceManager.GetString("UserNotification_NewClassBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Course has been booked !.
        /// </summary>
        internal static string UserNotification_NewCourseBookingMessage {
            get {
                return ResourceManager.GetString("UserNotification_NewCourseBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Booked Course!.
        /// </summary>
        internal static string UserNotification_NewCourseBookingTitle {
            get {
                return ResourceManager.GetString("UserNotification_NewCourseBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Event has been booked on {1} IST.
        /// </summary>
        internal static string UserNotification_NewEventBookingMessage {
            get {
                return ResourceManager.GetString("UserNotification_NewEventBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked Event - {0}.
        /// </summary>
        internal static string UserNotification_NewEventBookingTitle {
            get {
                return ResourceManager.GetString("UserNotification_NewEventBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Plan has been booked on {1} IST.
        /// </summary>
        internal static string UserNotification_NewPlanBookingMessage {
            get {
                return ResourceManager.GetString("UserNotification_NewPlanBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked Plan - {0}.
        /// </summary>
        internal static string UserNotification_NewPlanBookingTitle {
            get {
                return ResourceManager.GetString("UserNotification_NewPlanBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Training has been booked on {1} IST.
        /// </summary>
        internal static string UserNotification_NewTrainingBookingMessage {
            get {
                return ResourceManager.GetString("UserNotification_NewTrainingBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked Training - {0}.
        /// </summary>
        internal static string UserNotification_NewTrainingBookingTitle {
            get {
                return ResourceManager.GetString("UserNotification_NewTrainingBookingTitle", resourceCulture);
            }
        }
    }
}
