//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuperAdminPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuperAdminPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SuperAdminPanel", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Description Is Required.
        /// </summary>
        internal static string AboutDescriptionRequired {
            get {
                return ResourceManager.GetString("AboutDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Title Is Required.
        /// </summary>
        internal static string AboutTitleRequired {
            get {
                return ResourceManager.GetString("AboutTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status updated successfully!.
        /// </summary>
        internal static string AccountStatusUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("AccountStatusUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information is Required!.
        /// </summary>
        internal static string AdditionalInformationRequired {
            get {
                return ResourceManager.GetString("AdditionalInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address  Is Required!.
        /// </summary>
        internal static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, same email is already exist/used by other user!.
        /// </summary>
        internal static string AlreadyEmailExit_ErrorMessage {
            get {
                return ResourceManager.GetString("AlreadyEmailExit_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, same plan name already exists!.
        /// </summary>
        internal static string AlreadyPlanNameExists_ErrorMessage {
            get {
                return ResourceManager.GetString("AlreadyPlanNameExists_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category added successfully!.
        /// </summary>
        internal static string BusinessCategoryAdded_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessCategoryAdded_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category of same name already exists!.
        /// </summary>
        internal static string BusinessCategoryAlreadyExist_ErrorMessage {
            get {
                return ResourceManager.GetString("BusinessCategoryAlreadyExist_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category of same name already exists!.
        /// </summary>
        internal static string BusinessCategoryAlreadyExit_ErrorMessage {
            get {
                return ResourceManager.GetString("BusinessCategoryAlreadyExit_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category successfully deleted!.
        /// </summary>
        internal static string BusinessCategoryDeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessCategoryDeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category not exists!.
        /// </summary>
        internal static string BusinessCategoryNot_Exists {
            get {
                return ResourceManager.GetString("BusinessCategoryNot_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category status has been successfully updated!.
        /// </summary>
        internal static string BusinessCategoryStatus_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessCategoryStatus_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category updated successfully!.
        /// </summary>
        internal static string BusinessCategoryUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessCategoryUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category Not Found.
        /// </summary>
        internal static string BusinessCategory_ErrorMessage {
            get {
                return ResourceManager.GetString("BusinessCategory_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business classs Category successfully created!.
        /// </summary>
        internal static string BusinessClassCategoryCreatedMessage {
            get {
                return ResourceManager.GetString("BusinessClassCategoryCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Content Course Category  successfully!.
        /// </summary>
        internal static string BusinesscontentCourseCategoryCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinesscontentCourseCategoryCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessContentCourseCategory deleted successfully!.
        /// </summary>
        internal static string BusinessContentCourseCategorydeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessContentCourseCategorydeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessContentCourseCategory Update successfully!.
        /// </summary>
        internal static string BusinessContentCourseCategoryUpdate_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessContentCourseCategoryUpdate_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Content Education Service successfully!.
        /// </summary>
        internal static string BusinesscontentEducationCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinesscontentEducationCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessContentEducation deleted successfully!.
        /// </summary>
        internal static string BusinessContentEducationdeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessContentEducationdeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessContentEducation Update successfully!.
        /// </summary>
        internal static string BusinessContentEducationUpdate_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessContentEducationUpdate_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Content Language detail  successfully!.
        /// </summary>
        internal static string BusinesscontentLanguageCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinesscontentLanguageCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessContentLanguage deleted successfully!.
        /// </summary>
        internal static string BusinessContentLanguagedeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessContentLanguagedeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessContentLanguage Update successfully!.
        /// </summary>
        internal static string BusinessContentLanguageUpdate_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessContentLanguageUpdate_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Course Category Image Is Required.
        /// </summary>
        internal static string BusinessCourseCategoryImageRequired {
            get {
                return ResourceManager.GetString("BusinessCourseCategoryImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Language    same name already exists!.
        /// </summary>
        internal static string BusinessLanguageAlreadyExit_ErrorMessage {
            get {
                return ResourceManager.GetString("BusinessLanguageAlreadyExit_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added licenses to Business!.
        /// </summary>
        internal static string BusinessLicensesAdded_SuccessMessage {
            get {
                return ResourceManager.GetString("BusinessLicensesAdded_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Sponsor successfully created!.
        /// </summary>
        internal static string BusinessSponsorCreatedMessage {
            get {
                return ResourceManager.GetString("BusinessSponsorCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business University  same name already exists!.
        /// </summary>
        internal static string BusinessUniversityAlreadyExit_ErrorMessage {
            get {
                return ResourceManager.GetString("BusinessUniversityAlreadyExit_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business University Image Is Required.
        /// </summary>
        internal static string BusinessUniversityImageRequired {
            get {
                return ResourceManager.GetString("BusinessUniversityImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business University Logo Is Required.
        /// </summary>
        internal static string BusinessUniversityLogoRequired {
            get {
                return ResourceManager.GetString("BusinessUniversityLogoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button link is required!.
        /// </summary>
        internal static string ButtonLinkRequired {
            get {
                return ResourceManager.GetString("ButtonLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button text is required!.
        /// </summary>
        internal static string ButtonTextRequired {
            get {
                return ResourceManager.GetString("ButtonTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Icon Required!.
        /// </summary>
        internal static string CategoryIconRequired {
            get {
                return ResourceManager.GetString("CategoryIconRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Key Required!.
        /// </summary>
        internal static string CategoryKeyRequired_ErrorMessage {
            get {
                return ResourceManager.GetString("CategoryKeyRequired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name already exists!.
        /// </summary>
        internal static string CategoryNameAlreadyExist_ErrorMessage {
            get {
                return ResourceManager.GetString("CategoryNameAlreadyExist_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name Required!.
        /// </summary>
        internal static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate already assigned to this business!.
        /// </summary>
        internal static string CertificateAlreadyAssigned_ErrorMessage {
            get {
                return ResourceManager.GetString("CertificateAlreadyAssigned_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate has been successfully assigned!.
        /// </summary>
        internal static string CertificateAssigned_SuccessMessage {
            get {
                return ResourceManager.GetString("CertificateAssigned_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate created successfuly!.
        /// </summary>
        internal static string CertificateCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("CertificateCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate  deleted successfully!.
        /// </summary>
        internal static string CertificateDeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("CertificateDeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Icon is Required!.
        /// </summary>
        internal static string CertificateIconRequired {
            get {
                return ResourceManager.GetString("CertificateIconRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Link Is Required.
        /// </summary>
        internal static string CertificateLinkRequired {
            get {
                return ResourceManager.GetString("CertificateLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Name Is Rquired!.
        /// </summary>
        internal static string CertificateNameRequired {
            get {
                return ResourceManager.GetString("CertificateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is not assigned to this business!.
        /// </summary>
        internal static string CertificateNotAssigned_ErrorMessage {
            get {
                return ResourceManager.GetString("CertificateNotAssigned_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Price is Required!.
        /// </summary>
        internal static string CertificatePriceRequired {
            get {
                return ResourceManager.GetString("CertificatePriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select profile type!.
        /// </summary>
        internal static string CertificateProfilePageTypeRequired {
            get {
                return ResourceManager.GetString("CertificateProfilePageTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description is Required!.
        /// </summary>
        internal static string CertificateShortDescriptionRequired {
            get {
                return ResourceManager.GetString("CertificateShortDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate status has been successfully updated!.
        /// </summary>
        internal static string CertificateStatus_SuccessMessage {
            get {
                return ResourceManager.GetString("CertificateStatus_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate type is required!.
        /// </summary>
        internal static string CertificateTypeRequired {
            get {
                return ResourceManager.GetString("CertificateTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate has been successfully un-assigned!.
        /// </summary>
        internal static string CertificateUnAssigned_SuccessMessage {
            get {
                return ResourceManager.GetString("CertificateUnAssigned_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate updated successfuly!.
        /// </summary>
        internal static string CertificateUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("CertificateUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Category Description Is Required.
        /// </summary>
        internal static string ClassCategoryDescriptionRequired {
            get {
                return ResourceManager.GetString("ClassCategoryDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted!.
        /// </summary>
        internal static string ClassCategoryDetailsSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("ClassCategoryDetailsSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Category Icon IsRequired.
        /// </summary>
        internal static string ClassCategoryIconRequired {
            get {
                return ResourceManager.GetString("ClassCategoryIconRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Category Name Is Required.
        /// </summary>
        internal static string ClassCategoryNameRequired {
            get {
                return ResourceManager.GetString("ClassCategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class category type is required!.
        /// </summary>
        internal static string ClassCategoryTypeRequired {
            get {
                return ResourceManager.GetString("ClassCategoryTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Business Category!.
        /// </summary>
        internal static string ClassCategoryType_BusinessCategoryRequired {
            get {
                return ResourceManager.GetString("ClassCategoryType_BusinessCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class-Category-Type created successfully!.
        /// </summary>
        internal static string ClassCategoryType_Created_SuccessMessage {
            get {
                return ResourceManager.GetString("ClassCategoryType_Created_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class-Category-Type deleted successfully!.
        /// </summary>
        internal static string ClassCategoryType_Deleted_SuccessMessage {
            get {
                return ResourceManager.GetString("ClassCategoryType_Deleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Category-Type of same name already exists!.
        /// </summary>
        internal static string ClassCategoryType_NameAlreadyExist_ErrorMessage {
            get {
                return ResourceManager.GetString("ClassCategoryType_NameAlreadyExist_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required!.
        /// </summary>
        internal static string ClassCategoryType_NameRequired {
            get {
                return ResourceManager.GetString("ClassCategoryType_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category-Type not exists!.
        /// </summary>
        internal static string ClassCategoryType_NotExist_ErrorMessage {
            get {
                return ResourceManager.GetString("ClassCategoryType_NotExist_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Category-Type status has been successfully updated!.
        /// </summary>
        internal static string ClassCategoryType_StatusUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("ClassCategoryType_StatusUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class-Category-Type updated successfully!.
        /// </summary>
        internal static string ClassCategoryType_Updated_SuccessMessage {
            get {
                return ResourceManager.GetString("ClassCategoryType_Updated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassCategory successfully Updated!.
        /// </summary>
        internal static string ClassCategoryUpdatedMessage {
            get {
                return ResourceManager.GetString("ClassCategoryUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare-At-Price must be greater than Price!.
        /// </summary>
        internal static string CompareAtPriceMustGreaterThanPrice_ErrorMessage {
            get {
                return ResourceManager.GetString("CompareAtPriceMustGreaterThanPrice_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to approve this licence booking request?.
        /// </summary>
        internal static string ConfirmApproveLicenseBookingRequestText {
            get {
                return ResourceManager.GetString("ConfirmApproveLicenseBookingRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve License Booking.
        /// </summary>
        internal static string ConfirmApproveLicenseBookingRequestTitle {
            get {
                return ResourceManager.GetString("ConfirmApproveLicenseBookingRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to approve this payment request?.
        /// </summary>
        internal static string ConfirmApprovePaymentRequestText {
            get {
                return ResourceManager.GetString("ConfirmApprovePaymentRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Payment.
        /// </summary>
        internal static string ConfirmApprovePaymentRequestTitle {
            get {
                return ResourceManager.GetString("ConfirmApprovePaymentRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to block this Student?.
        /// </summary>
        internal static string ConfirmBlockUserText {
            get {
                return ResourceManager.GetString("ConfirmBlockUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block User.
        /// </summary>
        internal static string ConfirmBlockUserTitle {
            get {
                return ResourceManager.GetString("ConfirmBlockUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change status of this Advertisement?.
        /// </summary>
        internal static string ConfirmChangeStatusAdvertisementText {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusAdvertisementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        internal static string ConfirmChangeStatusAdvertisementTitle {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusAdvertisementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change status of this Category?.
        /// </summary>
        internal static string ConfirmChangeStatusCategoryText {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        internal static string ConfirmChangeStatusCategoryTitle {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change status of this Certificate?.
        /// </summary>
        internal static string ConfirmChangeStatusCertificatetext {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusCertificatetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        internal static string ConfirmChangeStatusCertificateTitle {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change status of this License?.
        /// </summary>
        internal static string ConfirmChangeStatusLicenseText {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        internal static string ConfirmChangeStatusLicenseTitle {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change status of this Menu?.
        /// </summary>
        internal static string ConfirmChangeStatusMenuText {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        internal static string ConfirmChangeStatusMenuTitle {
            get {
                return ResourceManager.GetString("ConfirmChangeStatusMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to decline this license booking request?.
        /// </summary>
        internal static string ConfirmDeclineLicenseBookingRequestText {
            get {
                return ResourceManager.GetString("ConfirmDeclineLicenseBookingRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline License Booking.
        /// </summary>
        internal static string ConfirmDeclineLicenseBookingRequestTitle {
            get {
                return ResourceManager.GetString("ConfirmDeclineLicenseBookingRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Advertisement?.
        /// </summary>
        internal static string ConfirmDeleteAdvertisementText {
            get {
                return ResourceManager.GetString("ConfirmDeleteAdvertisementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Advertisement.
        /// </summary>
        internal static string ConfirmDeleteAdvertisementTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteAdvertisementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Business Image?.
        /// </summary>
        internal static string ConfirmDeleteBusinessImageText {
            get {
                return ResourceManager.GetString("ConfirmDeleteBusinessImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Business Image.
        /// </summary>
        internal static string ConfirmDeleteBusinessImageTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteBusinessImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete Business Video?.
        /// </summary>
        internal static string ConfirmDeleteBusinessVideoText {
            get {
                return ResourceManager.GetString("ConfirmDeleteBusinessVideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Business Video.
        /// </summary>
        internal static string ConfirmDeleteBusinessVideoTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteBusinessVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to delete Class Category Detail ?.
        /// </summary>
        internal static string ConfirmDeleteClassCategoryText {
            get {
                return ResourceManager.GetString("ConfirmDeleteClassCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Class Category.
        /// </summary>
        internal static string ConfirmDeleteClassCategoryTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteClassCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Certificate?.
        /// </summary>
        internal static string ConfirmDeletedCertificateTextMessage {
            get {
                return ResourceManager.GetString("ConfirmDeletedCertificateTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Certificate.
        /// </summary>
        internal static string ConfirmDeletedCertificateTitleMessage {
            get {
                return ResourceManager.GetString("ConfirmDeletedCertificateTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to delete Course Category Detail.
        /// </summary>
        internal static string ConfirmDeleteDeleteCourseCategoryText {
            get {
                return ResourceManager.GetString("ConfirmDeleteDeleteCourseCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Course Category.
        /// </summary>
        internal static string ConfirmDeleteDeleteCourseCategoryTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteDeleteCourseCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this License?.
        /// </summary>
        internal static string ConfirmDeletedLicenseTextMessage {
            get {
                return ResourceManager.GetString("ConfirmDeletedLicenseTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete License.
        /// </summary>
        internal static string ConfirmDeletedLicenseTitleMessage {
            get {
                return ResourceManager.GetString("ConfirmDeletedLicenseTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Sub-Admin?.
        /// </summary>
        internal static string ConfirmDeletedSubAdminTextMessage {
            get {
                return ResourceManager.GetString("ConfirmDeletedSubAdminTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sub-Admin Record.
        /// </summary>
        internal static string ConfirmDeletedSubAdminTitleMessage {
            get {
                return ResourceManager.GetString("ConfirmDeletedSubAdminTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to delete Event Category Detail ?.
        /// </summary>
        internal static string ConfirmDeleteEventCategoryText {
            get {
                return ResourceManager.GetString("ConfirmDeleteEventCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Event Category.
        /// </summary>
        internal static string ConfirmDeleteEventCategoryTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteEventCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this item?.
        /// </summary>
        internal static string ConfirmDeleteItemText {
            get {
                return ResourceManager.GetString("ConfirmDeleteItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        internal static string ConfirmDeleteItemTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Business?.
        /// </summary>
        internal static string ConfirmDeleteManageBusinessText {
            get {
                return ResourceManager.GetString("ConfirmDeleteManageBusinessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Business.
        /// </summary>
        internal static string ConfirmDeleteManageBusinessTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteManageBusinessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete menu item?.
        /// </summary>
        internal static string ConfirmDeleteMenuText {
            get {
                return ResourceManager.GetString("ConfirmDeleteMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Menu.
        /// </summary>
        internal static string ConfirmDeleteMenuTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Sponsors?.
        /// </summary>
        internal static string ConfirmDeleteSponsorText {
            get {
                return ResourceManager.GetString("ConfirmDeleteSponsorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sponsor.
        /// </summary>
        internal static string ConfirmDeleteSponsorTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteSponsorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to delete Staff-Category?.
        /// </summary>
        internal static string ConfirmDeleteStaffCategoryText {
            get {
                return ResourceManager.GetString("ConfirmDeleteStaffCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Staff-Category.
        /// </summary>
        internal static string ConfirmDeleteStaffCategoryTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteStaffCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to delete university record .
        /// </summary>
        internal static string ConfirmDeleteUniversityText {
            get {
                return ResourceManager.GetString("ConfirmDeleteUniversityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete University.
        /// </summary>
        internal static string ConfirmDeleteUniversityTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteUniversityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this User Image?.
        /// </summary>
        internal static string ConfirmDeleteUserImageText {
            get {
                return ResourceManager.GetString("ConfirmDeleteUserImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User Image.
        /// </summary>
        internal static string ConfirmDeleteUserImageTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteUserImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Video?.
        /// </summary>
        internal static string ConfirmDeleteUserVideoText {
            get {
                return ResourceManager.GetString("ConfirmDeleteUserVideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Video.
        /// </summary>
        internal static string ConfirmDeleteUserVideoTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteUserVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Is Required !.
        /// </summary>
        internal static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change the visibility on Home page for this item?.
        /// </summary>
        internal static string ConfirmToggleHomePageVisibilityStatusTextMessage {
            get {
                return ResourceManager.GetString("ConfirmToggleHomePageVisibilityStatusTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Home Visibility Status.
        /// </summary>
        internal static string ConfirmToggleHomePageVisibilityStatusTitleMessage {
            get {
                return ResourceManager.GetString("ConfirmToggleHomePageVisibilityStatusTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to unblock this Student?.
        /// </summary>
        internal static string ConfirmUnBlockUserText {
            get {
                return ResourceManager.GetString("ConfirmUnBlockUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock User.
        /// </summary>
        internal static string ConfirmUnBlockUserTitle {
            get {
                return ResourceManager.GetString("ConfirmUnBlockUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Description Is Required.
        /// </summary>
        internal static string ContactDescriptionRequired {
            get {
                return ResourceManager.GetString("ContactDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details inserted successfully!.
        /// </summary>
        internal static string ContactDetailInserted_SuccessMessage {
            get {
                return ResourceManager.GetString("ContactDetailInserted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Detailed updated successfully!.
        /// </summary>
        internal static string ContactDetailUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("ContactDetailUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number 1 Is Required.
        /// </summary>
        internal static string ContactNumber1Required {
            get {
                return ResourceManager.GetString("ContactNumber1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number 2 Is Required.
        /// </summary>
        internal static string ContactNumber2Required {
            get {
                return ResourceManager.GetString("ContactNumber2Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number 3 Is Required.
        /// </summary>
        internal static string ContactNumber3Required {
            get {
                return ResourceManager.GetString("ContactNumber3Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number 4 Is Required.
        /// </summary>
        internal static string ContactNumber4Required {
            get {
                return ResourceManager.GetString("ContactNumber4Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number 5 Is Required.
        /// </summary>
        internal static string ContactNumber5Required {
            get {
                return ResourceManager.GetString("ContactNumber5Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number 6 Is Required.
        /// </summary>
        internal static string ContactNumber6Required {
            get {
                return ResourceManager.GetString("ContactNumber6Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number 7 Is Required.
        /// </summary>
        internal static string ContactNumber7Required {
            get {
                return ResourceManager.GetString("ContactNumber7Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number 8 Is Required.
        /// </summary>
        internal static string ContactNumber8Required {
            get {
                return ResourceManager.GetString("ContactNumber8Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number will not contain any empty/white space is required!.
        /// </summary>
        internal static string ContactNumberNotEmptySpaceRequired {
            get {
                return ResourceManager.GetString("ContactNumberNotEmptySpaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactNumber  Is Required.
        /// </summary>
        internal static string ContactNumberRequired {
            get {
                return ResourceManager.GetString("ContactNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts created successfully!.
        /// </summary>
        internal static string ContactsCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("ContactsCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Update successfully!.
        /// </summary>
        internal static string ContactsUpdate_SuccessMessage {
            get {
                return ResourceManager.GetString("ContactsUpdate_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title Is Required.
        /// </summary>
        internal static string ContactTitleRequired {
            get {
                return ResourceManager.GetString("ContactTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created successfully!.
        /// </summary>
        internal static string Created_SuccessMessage {
            get {
                return ResourceManager.GetString("Created_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Form already assigned to this business!.
        /// </summary>
        internal static string CustomFormAlreadyAssigned_ErrorMessage {
            get {
                return ResourceManager.GetString("CustomFormAlreadyAssigned_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Form has been successfully assigned!.
        /// </summary>
        internal static string CustomFormAssigned_SuccessMessage {
            get {
                return ResourceManager.GetString("CustomFormAssigned_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Form is not assigned to this business!.
        /// </summary>
        internal static string CustomFormNotAssigned_ErrorMessage {
            get {
                return ResourceManager.GetString("CustomFormNotAssigned_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Form has been successfully un-assigned!.
        /// </summary>
        internal static string CustomFormUnAssigned_SuccessMessage {
            get {
                return ResourceManager.GetString("CustomFormUnAssigned_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item deleted successfully!.
        /// </summary>
        internal static string Deleted_SuccessMessage {
            get {
                return ResourceManager.GetString("Deleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Is Required.
        /// </summary>
        internal static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required!.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Is Required.
        /// </summary>
        internal static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Category Status has been successfully updated!.
        /// </summary>
        internal static string EventCategoryType_StatusUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("EventCategoryType_StatusUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something exception occurred!.
        /// </summary>
        internal static string ExceptionOccured_ErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionOccured_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature limit is required!.
        /// </summary>
        internal static string FeatureLimitRequired {
            get {
                return ResourceManager.GetString("FeatureLimitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName Is Required.
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *HPV: Home Page Visibility (to make it visible on Home Page).
        /// </summary>
        internal static string HomePageVisibilityDefination {
            get {
                return ResourceManager.GetString("HomePageVisibilityDefination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page visibility status updated successfully!.
        /// </summary>
        internal static string HomePageVisibilityStatusUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("HomePageVisibilityStatusUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is Required!.
        /// </summary>
        internal static string ImageRequired {
            get {
                return ResourceManager.GetString("ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid active status.
        /// </summary>
        internal static string InvalidActiveStatusRequired {
            get {
                return ResourceManager.GetString("InvalidActiveStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parent Category.
        /// </summary>
        internal static string InvalidParentCategoryRequired {
            get {
                return ResourceManager.GetString("InvalidParentCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parent Category!.
        /// </summary>
        internal static string InvalidParentCategory_ErrorMessage {
            get {
                return ResourceManager.GetString("InvalidParentCategory_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Checked Required!.
        /// </summary>
        internal static string IsActiveCategoryRequired {
            get {
                return ResourceManager.GetString("IsActiveCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName Is Required.
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Achieving Order already exists!.
        /// </summary>
        internal static string LicenseAchievingOrderAlreadyExists_ErrorMessage {
            get {
                return ResourceManager.GetString("LicenseAchievingOrderAlreadyExists_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License booking request approved successfully!.
        /// </summary>
        internal static string LicenseBookingRequestApproved_SuccessMessage {
            get {
                return ResourceManager.GetString("LicenseBookingRequestApproved_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Created successfuly!.
        /// </summary>
        internal static string LicenseCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("LicenseCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License deleted successfully!.
        /// </summary>
        internal static string LicenseDeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("LicenseDeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License status updated successfully!.
        /// </summary>
        internal static string LicenseStatusUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("LicenseStatusUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License of same title already exists!.
        /// </summary>
        internal static string LicenseTitleAlreadyExist_ErrorMessage {
            get {
                return ResourceManager.GetString("LicenseTitleAlreadyExist_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License To Teach Display Name Is Required.
        /// </summary>
        internal static string LicenseToTeachDisplayNameRequired {
            get {
                return ResourceManager.GetString("LicenseToTeachDisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License To Teach Display Type Is Required.
        /// </summary>
        internal static string LicenseToTeachDisplayRequired {
            get {
                return ResourceManager.GetString("LicenseToTeachDisplayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License To Teach Is Required.
        /// </summary>
        internal static string LicenseToTeachRequired {
            get {
                return ResourceManager.GetString("LicenseToTeachRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Updated successfuly!.
        /// </summary>
        internal static string LicenseUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("LicenseUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Achieving order is required!.
        /// </summary>
        internal static string License_AchievingOrderRequired {
            get {
                return ResourceManager.GetString("License_AchievingOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Image is required!.
        /// </summary>
        internal static string License_CertificateImageRequired {
            get {
                return ResourceManager.GetString("License_CertificateImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the certification profile!.
        /// </summary>
        internal static string License_CertificateSelectionRequired {
            get {
                return ResourceManager.GetString("License_CertificateSelectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission type selection required!.
        /// </summary>
        internal static string License_CommissionTypeRequired {
            get {
                return ResourceManager.GetString("License_CommissionTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission value must be greater than zero!.
        /// </summary>
        internal static string License_CommissionValueGreaterThanZeroRequired {
            get {
                return ResourceManager.GetString("License_CommissionValueGreaterThanZeroRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required!.
        /// </summary>
        internal static string License_DescriptionRequired {
            get {
                return ResourceManager.GetString("License_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the certificate HTML content..
        /// </summary>
        internal static string License_LicenseCertificateHTMLContentRequired {
            get {
                return ResourceManager.GetString("License_LicenseCertificateHTMLContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Logo is required!.
        /// </summary>
        internal static string License_LicenseLogoImageRequired {
            get {
                return ResourceManager.GetString("License_LicenseLogoImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License MasterPro Is Required.
        /// </summary>
        internal static string License_MasterProRequired {
            get {
                return ResourceManager.GetString("License_MasterProRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. selling price is required and can&apos;t be less than zero..
        /// </summary>
        internal static string License_MinimunSellingPriceRequired {
            get {
                return ResourceManager.GetString("License_MinimunSellingPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select altleast one  License_Permisions   Is Required.
        /// </summary>
        internal static string License_PermisionsRequired {
            get {
                return ResourceManager.GetString("License_PermisionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License price is required!.
        /// </summary>
        internal static string License_PriceRequired {
            get {
                return ResourceManager.GetString("License_PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Image is required!.
        /// </summary>
        internal static string License_SignatureImageRequired {
            get {
                return ResourceManager.GetString("License_SignatureImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Time period is required!.
        /// </summary>
        internal static string License_TimePeriodRequired {
            get {
                return ResourceManager.GetString("License_TimePeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required!.
        /// </summary>
        internal static string License_TitleRequired {
            get {
                return ResourceManager.GetString("License_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location 1 Is Required.
        /// </summary>
        internal static string Location1Required {
            get {
                return ResourceManager.GetString("Location1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location 2 Is Required.
        /// </summary>
        internal static string Location2Required {
            get {
                return ResourceManager.GetString("Location2Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location 3 Is Required.
        /// </summary>
        internal static string Location3Required {
            get {
                return ResourceManager.GetString("Location3Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location 4 Is Required.
        /// </summary>
        internal static string Location4Required {
            get {
                return ResourceManager.GetString("Location4Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location 5 Is Required.
        /// </summary>
        internal static string Location5Required {
            get {
                return ResourceManager.GetString("Location5Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location 6 Is Required.
        /// </summary>
        internal static string Location6Required {
            get {
                return ResourceManager.GetString("Location6Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location 7 Is Required.
        /// </summary>
        internal static string Location7Required {
            get {
                return ResourceManager.GetString("Location7Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location  8 Is Required.
        /// </summary>
        internal static string Location8Required {
            get {
                return ResourceManager.GetString("Location8Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu added successfully!.
        /// </summary>
        internal static string MenuAdded_SuccessMessage {
            get {
                return ResourceManager.GetString("MenuAdded_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu deleted successfully!.
        /// </summary>
        internal static string MenuDeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("MenuDeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu icon required!.
        /// </summary>
        internal static string MenuIconRequired {
            get {
                return ResourceManager.GetString("MenuIconRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu name required!.
        /// </summary>
        internal static string MenuNameRequired {
            get {
                return ResourceManager.GetString("MenuNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu not found!.
        /// </summary>
        internal static string MenuNotFound_ErrorMessage {
            get {
                return ResourceManager.GetString("MenuNotFound_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Link Required!.
        /// </summary>
        internal static string MenuPageLinkRequired {
            get {
                return ResourceManager.GetString("MenuPageLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Sort Order Is Required.
        /// </summary>
        internal static string MenuSortOrderRequired {
            get {
                return ResourceManager.GetString("MenuSortOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu status changed successfully!.
        /// </summary>
        internal static string MenuStatusChanged_SuccessMessage {
            get {
                return ResourceManager.GetString("MenuStatusChanged_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu tag required!.
        /// </summary>
        internal static string MenuTagRequired {
            get {
                return ResourceManager.GetString("MenuTagRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu updated successfully!.
        /// </summary>
        internal static string MenuUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("MenuUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu of same name already exists!.
        /// </summary>
        internal static string Menu_SameNameAlreadyExit_ErrorMessage {
            get {
                return ResourceManager.GetString("Menu_SameNameAlreadyExit_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same tag already exists!.
        /// </summary>
        internal static string Menu_SameTagAlreadyExit_ErrorMessage {
            get {
                return ResourceManager.GetString("Menu_SameTagAlreadyExit_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission About Description Is Required.
        /// </summary>
        internal static string MissionAboutDescriptionRequired {
            get {
                return ResourceManager.GetString("MissionAboutDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission About Title Is Required.
        /// </summary>
        internal static string MissionAboutTitleRequired {
            get {
                return ResourceManager.GetString("MissionAboutTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a numeric value!.
        /// </summary>
        internal static string NumericValueRequired {
            get {
                return ResourceManager.GetString("NumericValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a category!.
        /// </summary>
        internal static string ParentBusinessCategoryRequired {
            get {
                return ResourceManager.GetString("ParentBusinessCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Is Required!.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Response Approved status updated successfully!.
        /// </summary>
        internal static string PaymentResponseApprovedStatusUpdate_SuccessMessage {
            get {
                return ResourceManager.GetString("PaymentResponseApprovedStatusUpdate_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Is Required.
        /// </summary>
        internal static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan created successfully!.
        /// </summary>
        internal static string PlanCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("PlanCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan deleted successfully!.
        /// </summary>
        internal static string PlanDeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("PlanDeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Required!.
        /// </summary>
        internal static string PlanDescriptionRequired {
            get {
                return ResourceManager.GetString("PlanDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Plan Duration!.
        /// </summary>
        internal static string PlanDurationTypeRequired {
            get {
                return ResourceManager.GetString("PlanDurationTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Name Required!.
        /// </summary>
        internal static string PlanNameRequired {
            get {
                return ResourceManager.GetString("PlanNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan not created. Something went wrong!.
        /// </summary>
        internal static string PlanNotCreated_ErrorMessage {
            get {
                return ResourceManager.GetString("PlanNotCreated_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Plan not Found!.
        /// </summary>
        internal static string PlanNotFound_ErrorMessage {
            get {
                return ResourceManager.GetString("PlanNotFound_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan not updated. Something went wrong!.
        /// </summary>
        internal static string PlanNotUpdated_ErrorMessage {
            get {
                return ResourceManager.GetString("PlanNotUpdated_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Required.
        /// </summary>
        internal static string PlanPriceRequired {
            get {
                return ResourceManager.GetString("PlanPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than zero.
        /// </summary>
        internal static string PlanPriceValueRequired {
            get {
                return ResourceManager.GetString("PlanPriceValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan status has been successfully updated.
        /// </summary>
        internal static string PlanStatusUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("PlanStatusUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Plan Type!.
        /// </summary>
        internal static string PlanTypeRequired {
            get {
                return ResourceManager.GetString("PlanTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan updated successfully!.
        /// </summary>
        internal static string PlanUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("PlanUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image!.
        /// </summary>
        internal static string PleaseSelectAnImage_ErrorMessage {
            get {
                return ResourceManager.GetString("PleaseSelectAnImage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Page Type Required!.
        /// </summary>
        internal static string ProfilePageTypeRequired_ErrorMessage {
            get {
                return ResourceManager.GetString("ProfilePageTypeRequired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification Is Required.
        /// </summary>
        internal static string QualificationRequired {
            get {
                return ResourceManager.GetString("QualificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Advertisement Is Required.
        /// </summary>
        internal static string SelectAdvertisementRequired {
            get {
                return ResourceManager.GetString("SelectAdvertisementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  Category Is Required.
        /// </summary>
        internal static string SelectCategoryRequired {
            get {
                return ResourceManager.GetString("SelectCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image Is Required.
        /// </summary>
        internal static string SelectImageRequired {
            get {
                return ResourceManager.GetString("SelectImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted!.
        /// </summary>
        internal static string SponsorDetailsSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SponsorDetailsSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Icon Is Required.
        /// </summary>
        internal static string SponsorIconRequired {
            get {
                return ResourceManager.GetString("SponsorIconRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Link Is Required.
        /// </summary>
        internal static string SponsorLinkRequired {
            get {
                return ResourceManager.GetString("SponsorLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Title Is Required.
        /// </summary>
        internal static string SponsorTitleRequired {
            get {
                return ResourceManager.GetString("SponsorTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor successfully Updated!.
        /// </summary>
        internal static string SponsorUpdatedMessage {
            get {
                return ResourceManager.GetString("SponsorUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Category Status has been successfully updated!.
        /// </summary>
        internal static string StaffCategoryType_StatusUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("StaffCategoryType_StatusUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Is Required.
        /// </summary>
        internal static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status updated successfully!.
        /// </summary>
        internal static string StatusUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("StatusUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAdmin has been deleted successfully!.
        /// </summary>
        internal static string SubAdminDeleteMessage {
            get {
                return ResourceManager.GetString("SubAdminDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAdmin Icon Required.
        /// </summary>
        internal static string SubAdminIconRequired {
            get {
                return ResourceManager.GetString("SubAdminIconRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAdmin Profile Image Updated successfuly!.
        /// </summary>
        internal static string SubAdminProfileImageUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("SubAdminProfileImageUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAdmin Profile Updated successfuly!.
        /// </summary>
        internal static string SubAdminProfileUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("SubAdminProfileUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAdmin successfully created!.
        /// </summary>
        internal static string SubAdminSuccessfullyCreated {
            get {
                return ResourceManager.GetString("SubAdminSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAdmin updated successfully!.
        /// </summary>
        internal static string SubAdminSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SubAdminSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Is Required!.
        /// </summary>
        internal static string SubAdmin_CityRequired {
            get {
                return ResourceManager.GetString("SubAdmin_CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Is Required!.
        /// </summary>
        internal static string SubAdmin_CountryRequired {
            get {
                return ResourceManager.GetString("SubAdmin_CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Is Required!.
        /// </summary>
        internal static string SubAdmin_FirstNameRequired {
            get {
                return ResourceManager.GetString("SubAdmin_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandMark Is Required!.
        /// </summary>
        internal static string SubAdmin_LandmarkRequired {
            get {
                return ResourceManager.GetString("SubAdmin_LandmarkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Is Required!.
        /// </summary>
        internal static string SubAdmin_LastNameRequired {
            get {
                return ResourceManager.GetString("SubAdmin_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Is Required!.
        /// </summary>
        internal static string SubAdmin_LocationRequired {
            get {
                return ResourceManager.GetString("SubAdmin_LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose atleast one Permission Is Required.
        /// </summary>
        internal static string SubAdmin_PermisionsRequired {
            get {
                return ResourceManager.GetString("SubAdmin_PermisionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code Is Required!.
        /// </summary>
        internal static string SubAdmin_PincodeRequired {
            get {
                return ResourceManager.GetString("SubAdmin_PincodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Is Required!.
        /// </summary>
        internal static string SubAdmin_StateRequired {
            get {
                return ResourceManager.GetString("SubAdmin_StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About details created successfully!.
        /// </summary>
        internal static string SuperAdminAboutAboutCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("SuperAdminAboutAboutCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About details Update successfully!.
        /// </summary>
        internal static string SuperAdminAboutUpdate_SuccessMessage {
            get {
                return ResourceManager.GetString("SuperAdminAboutUpdate_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin Profile Image Updated successfuly!.
        /// </summary>
        internal static string SuperAdminProfileImageUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("SuperAdminProfileImageUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin Profile Updated successfuly!.
        /// </summary>
        internal static string SuperAdminProfileUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("SuperAdminProfileUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile error!.
        /// </summary>
        internal static string SuperAdminProfile_ErrorMessage {
            get {
                return ResourceManager.GetString("SuperAdminProfile_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category has been deleted successfully!.
        /// </summary>
        internal static string SwalDeleteCategory {
            get {
                return ResourceManager.GetString("SwalDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string SwalTitle {
            get {
                return ResourceManager.GetString("SwalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is required!.
        /// </summary>
        internal static string TextRequired {
            get {
                return ResourceManager.GetString("TextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Is Required.
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University Id Is Required.
        /// </summary>
        internal static string UniversityIdRequired {
            get {
                return ResourceManager.GetString("UniversityIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University Is Required.
        /// </summary>
        internal static string UniversityRequired {
            get {
                return ResourceManager.GetString("UniversityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully!.
        /// </summary>
        internal static string Updated_SuccessMessage {
            get {
                return ResourceManager.GetString("Updated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already blocked!.
        /// </summary>
        internal static string UserAlreadyBlocked_ErrorMessage {
            get {
                return ResourceManager.GetString("UserAlreadyBlocked_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User blocked successfully!.
        /// </summary>
        internal static string UserBlocked_SuccessMessage {
            get {
                return ResourceManager.GetString("UserBlocked_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserImage Delete Successfully!.
        /// </summary>
        internal static string UserImageDeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("UserImageDeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User unblocked successfully!.
        /// </summary>
        internal static string UserUnBlocked_SuccessMessage {
            get {
                return ResourceManager.GetString("UserUnBlocked_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserVedio Delete Successfully!.
        /// </summary>
        internal static string UserVedioDeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("UserVedioDeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid ContactNumber  Is Required.
        /// </summary>
        internal static string ValidContactNumberRequired {
            get {
                return ResourceManager.GetString("ValidContactNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Email!.
        /// </summary>
        internal static string ValidEmailRequired {
            get {
                return ResourceManager.GetString("ValidEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size too large. Please select a smaller image. (upto {0}).
        /// </summary>
        internal static string ValidFileSize_ErrorMessage {
            get {
                return ResourceManager.GetString("ValidFileSize_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image type. Please select a JPEG, PNG.
        /// </summary>
        internal static string ValidImageFile_ErrorMessage {
            get {
                return ResourceManager.GetString("ValidImageFile_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid HTTP link.
        /// </summary>
        internal static string ValidLinkRequired {
            get {
                return ResourceManager.GetString("ValidLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please Enter Valid PhoneNumber Is Required.
        /// </summary>
        internal static string ValidPhoneNumberRequired {
            get {
                return ResourceManager.GetString("ValidPhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video link is required!.
        /// </summary>
        internal static string VideoLinkRequired {
            get {
                return ResourceManager.GetString("VideoLinkRequired", resourceCulture);
            }
        }
    }
}
