//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VisitorPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisitorPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.VisitorPanel", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to Favourites!.
        /// </summary>
        internal static string AddedFavourites_ErrorMessage {
            get {
                return ResourceManager.GetString("AddedFavourites_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followed successfully!.
        /// </summary>
        internal static string AddedFollower_SuccessMessage {
            get {
                return ResourceManager.GetString("AddedFollower_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, same email is already exist/used by other user!.
        /// </summary>
        internal static string AlreadyEmailExit_ErrorMessage {
            get {
                return ResourceManager.GetString("AlreadyEmailExit_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Is Required.
        /// </summary>
        internal static string ApartmentRequired {
            get {
                return ResourceManager.GetString("ApartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked Id Is Required.
        /// </summary>
        internal static string BookedIdRequired {
            get {
                return ResourceManager.GetString("BookedIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card details update successfully!.
        /// </summary>
        internal static string CardDetailsUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("CardDetailsUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Name  Is Required.
        /// </summary>
        internal static string CardNameRequired {
            get {
                return ResourceManager.GetString("CardNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number Is Required.
        /// </summary>
        internal static string CardNumberRequired {
            get {
                return ResourceManager.GetString("CardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Id Required.
        /// </summary>
        internal static string CategoryIdRequired {
            get {
                return ResourceManager.GetString("CategoryIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been sent to your email for verification!.
        /// </summary>
        internal static string ConfirmationEmailSent_SuccessMessage {
            get {
                return ResourceManager.GetString("ConfirmationEmailSent_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Account.
        /// </summary>
        internal static string ConfirmDeleteAccountText {
            get {
                return ResourceManager.GetString("ConfirmDeleteAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string ConfirmDeleteAccountTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to Delete this user content video ?.
        /// </summary>
        internal static string ConfirmDeletedContentVideoTextMessage {
            get {
                return ResourceManager.GetString("ConfirmDeletedContentVideoTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content User Vedio .
        /// </summary>
        internal static string ConfirmDeletedContentVideoTitleMessage {
            get {
                return ResourceManager.GetString("ConfirmDeletedContentVideoTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Enquiry.
        /// </summary>
        internal static string ConfirmDeleteEnquiryText {
            get {
                return ResourceManager.GetString("ConfirmDeleteEnquiryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Enquiry.
        /// </summary>
        internal static string ConfirmDeleteEnquiryTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteEnquiryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Notification?.
        /// </summary>
        internal static string ConfirmDeleteNotificationText {
            get {
                return ResourceManager.GetString("ConfirmDeleteNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Notification.
        /// </summary>
        internal static string ConfirmDeleteNotificationTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this query?.
        /// </summary>
        internal static string ConfirmDeleteQueryText {
            get {
                return ResourceManager.GetString("ConfirmDeleteQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Query.
        /// </summary>
        internal static string ConfirmDeleteQueryTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteQueryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Is Required.
        /// </summary>
        internal static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favourite list.
        /// </summary>
        internal static string ConfirmRemoveFavourite {
            get {
                return ResourceManager.GetString("ConfirmRemoveFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details inserted successfully!.
        /// </summary>
        internal static string ContactDetailInserted_SuccessMessage {
            get {
                return ResourceManager.GetString("ContactDetailInserted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Detailed updated successfully!.
        /// </summary>
        internal static string ContactDetailUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("ContactDetailUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent successfully!.
        /// </summary>
        internal static string Contact_SuccessMessage {
            get {
                return ResourceManager.GetString("Contact_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon already used!.
        /// </summary>
        internal static string CouponAlreadyUsed_ErrorMessage {
            get {
                return ResourceManager.GetString("CouponAlreadyUsed_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Applied!.
        /// </summary>
        internal static string CouponApplied_SuccessMessage {
            get {
                return ResourceManager.GetString("CouponApplied_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Code Required!.
        /// </summary>
        internal static string CouponCodeRequired {
            get {
                return ResourceManager.GetString("CouponCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon consumed successfully!.
        /// </summary>
        internal static string CouponConsumed_SucccessMessage {
            get {
                return ResourceManager.GetString("CouponConsumed_SucccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon has been expired!.
        /// </summary>
        internal static string CouponExpired_ErrorMessage {
            get {
                return ResourceManager.GetString("CouponExpired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get data!.
        /// </summary>
        internal static string DataNot_Found_ErrorMessage {
            get {
                return ResourceManager.GetString("DataNot_Found_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Is Required.
        /// </summary>
        internal static string DepartmentRequired {
            get {
                return ResourceManager.GetString("DepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Is Required!.
        /// </summary>
        internal static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Required.
        /// </summary>
        internal static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been verifed!.
        /// </summary>
        internal static string EmailConfirmedMessage {
            get {
                return ResourceManager.GetString("EmailConfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  Is Required!.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is Required.
        /// </summary>
        internal static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Delete Successfully!.
        /// </summary>
        internal static string EnquiryDeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("EnquiryDeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not get data. Try Again later!.
        /// </summary>
        internal static string EnquiryDoesNotGetData_ErrorMessage {
            get {
                return ResourceManager.GetString("EnquiryDoesNotGetData_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry added successfuly!.
        /// </summary>
        internal static string EnquiryInserted_SuccessMessage {
            get {
                return ResourceManager.GetString("EnquiryInserted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry not found!.
        /// </summary>
        internal static string EnquiryNotFound_ErrorMessage {
            get {
                return ResourceManager.GetString("EnquiryNotFound_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry updated successfully!.
        /// </summary>
        internal static string EnquiryUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("EnquiryUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Form submitted successfully!.
        /// </summary>
        internal static string ExamFormSubmit_Insert_SuccessMessage {
            get {
                return ResourceManager.GetString("ExamFormSubmit_Insert_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Aadhar Card Number!.
        /// </summary>
        internal static string ExamForm_AadharCardNo_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_AadharCardNo_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Fee Amount in words!.
        /// </summary>
        internal static string ExamForm_AmountInWord_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_AmountInWord_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Fee Amount!.
        /// </summary>
        internal static string ExamForm_Amount_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_Amount_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Bank Draft Date!.
        /// </summary>
        internal static string ExamForm_BankDraftDate_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_BankDraftDate_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Bank Draft Number!.
        /// </summary>
        internal static string ExamForm_BankDraftNo_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_BankDraftNo_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Father&apos;s name!.
        /// </summary>
        internal static string ExamForm_CandidateFather_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateFather_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Guardian Name!.
        /// </summary>
        internal static string ExamForm_CandidateGuradianName_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateGuradianName_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Guardian Signature: Image size too large. Please select a smaller image(&lt; {0})..
        /// </summary>
        internal static string ExamForm_CandidateGuradianSignature_FileSizeRequired_ErrorMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateGuradianSignature_FileSizeRequired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Guradian Signature!.
        /// </summary>
        internal static string ExamForm_CandidateGuradianSignature_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateGuradianSignature_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Guardian Signature: Invalid image type. Please select a JPEG, PNG image..
        /// </summary>
        internal static string ExamForm_CandidateGuradianSignature_ValidImageTypesRequired_ErrorMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateGuradianSignature_ValidImageTypesRequired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Mother&apos;s name!.
        /// </summary>
        internal static string ExamForm_CandidateMother_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateMother_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Candidate Name!.
        /// </summary>
        internal static string ExamForm_CandidateName_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateName_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Image: Image size too large. Please select a smaller image(&lt; {0})..
        /// </summary>
        internal static string ExamForm_CandidateProfileImage_FileSizeRequired_ErrorMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateProfileImage_FileSizeRequired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Candidate Image!.
        /// </summary>
        internal static string ExamForm_CandidateProfileImage_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateProfileImage_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Image: Invalid image type. Please select a JPEG, PNG image..
        /// </summary>
        internal static string ExamForm_CandidateProfileImage_ValidImageTypesRequired_ErrorMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateProfileImage_ValidImageTypesRequired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Signature: Image size too large. Please select a smaller image(&lt; {0})..
        /// </summary>
        internal static string ExamForm_CandidateSignature_FileSizeRequired_ErrorMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateSignature_FileSizeRequired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Candidate Signature!.
        /// </summary>
        internal static string ExamForm_CandidateSignature_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateSignature_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Signature: Invalid image type. Please select a JPEG, PNG image..
        /// </summary>
        internal static string ExamForm_CandidateSignature_ValidImageTypesRequired_ErrorMessage {
            get {
                return ResourceManager.GetString("ExamForm_CandidateSignature_ValidImageTypesRequired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Category!.
        /// </summary>
        internal static string ExamForm_Category_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_Category_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter marksheet and certificate required at home address or through center superintendent!.
        /// </summary>
        internal static string ExamForm_CertificateCollectFrom_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CertificateCollectFrom_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Examination Center City!.
        /// </summary>
        internal static string ExamForm_CurrentCenterCity_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CurrentCenterCity_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Examination Center Name!.
        /// </summary>
        internal static string ExamForm_CurrentCenterName_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CurrentCenterName_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Examination Class!.
        /// </summary>
        internal static string ExamForm_CurrentClass_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CurrentClass_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Examination Roll-Number!.
        /// </summary>
        internal static string ExamForm_CurrentRollNo_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CurrentRollNo_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Examination Subject Name!.
        /// </summary>
        internal static string ExamForm_CurrentSubject_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_CurrentSubject_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Date Of Birth!.
        /// </summary>
        internal static string ExamForm_DOB_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_DOB_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Education Qualification!.
        /// </summary>
        internal static string ExamForm_EduQualification_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_EduQualification_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Candidate Email!.
        /// </summary>
        internal static string ExamForm_Email_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_Email_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Nationality!.
        /// </summary>
        internal static string ExamForm_Nationality_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_Nationality_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number of enclosures attatched!.
        /// </summary>
        internal static string ExamForm_NoOfAttached_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_NoOfAttached_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter permanent address!.
        /// </summary>
        internal static string ExamForm_PermanentAddress_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PermanentAddress_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter permanent mobile number!.
        /// </summary>
        internal static string ExamForm_PermanentMobNo_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PermanentMobNo_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter permanent address pincode!.
        /// </summary>
        internal static string ExamForm_PermanentPin_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PermanentPin_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Postal Order Number!.
        /// </summary>
        internal static string ExamForm_PostalOrderNo_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PostalOrderNo_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter present address!.
        /// </summary>
        internal static string ExamForm_PresentAddress_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PresentAddress_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter present mobile number!.
        /// </summary>
        internal static string ExamForm_PresentMobNo_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PresentMobNo_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter present address pincode!.
        /// </summary>
        internal static string ExamForm_PresentPin_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PresentPin_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter previous examination center name!.
        /// </summary>
        internal static string ExamForm_PreviousCenterName_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PreviousCenterName_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter previous examination class name!.
        /// </summary>
        internal static string ExamForm_PreviousClass_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PreviousClass_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter previous examination result!.
        /// </summary>
        internal static string ExamForm_PreviousResult_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PreviousResult_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter previous examination roll number!.
        /// </summary>
        internal static string ExamForm_PreviousRollNo_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PreviousRollNo_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter previous examination subject!.
        /// </summary>
        internal static string ExamForm_PreviousSubject_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PreviousSubject_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter previous examination year!.
        /// </summary>
        internal static string ExamForm_PreviousYear_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_PreviousYear_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter session year!.
        /// </summary>
        internal static string ExamForm_SessionYear_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_SessionYear_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter superintendent email!.
        /// </summary>
        internal static string ExamForm_SuperintendentEmail_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_SuperintendentEmail_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter superintendent name!.
        /// </summary>
        internal static string ExamForm_SuperintendentName_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_SuperintendentName_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter superintendent phone number!.
        /// </summary>
        internal static string ExamForm_SuperintendentPhoneNo_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_SuperintendentPhoneNo_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter superintendent pincode!.
        /// </summary>
        internal static string ExamForm_SuperintendentPinNo_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_SuperintendentPinNo_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload superintendent signature!.
        /// </summary>
        internal static string ExamForm_SuperintendentSignature_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_SuperintendentSignature_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Master-Id.
        /// </summary>
        internal static string ExamForm_UserMasterId_RequiredMessage {
            get {
                return ResourceManager.GetString("ExamForm_UserMasterId_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Month  Is Required.
        /// </summary>
        internal static string ExpiryMonthRequired {
            get {
                return ResourceManager.GetString("ExpiryMonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Year Is Required!.
        /// </summary>
        internal static string ExpiryYearRequired {
            get {
                return ResourceManager.GetString("ExpiryYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Is Required!.
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Is Required.
        /// </summary>
        internal static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Number Is Required.
        /// </summary>
        internal static string HouseNumberRequired {
            get {
                return ResourceManager.GetString("HouseNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Coupon!.
        /// </summary>
        internal static string InvalidCoupon {
            get {
                return ResourceManager.GetString("InvalidCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Item Type!.
        /// </summary>
        internal static string InvalidOrderItemType_ErrorMessage {
            get {
                return ResourceManager.GetString("InvalidOrderItemType_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName Is  Required!.
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude &amp; Longitude values are required!.
        /// </summary>
        internal static string LatitudeLongitudeValuesRequired {
            get {
                return ResourceManager.GetString("LatitudeLongitudeValuesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to book the class!.
        /// </summary>
        internal static string LoginBookClass_ErrrorMessage {
            get {
                return ResourceManager.GetString("LoginBookClass_ErrrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Id is required!.
        /// </summary>
        internal static string MasterId_Required {
            get {
                return ResourceManager.GetString("MasterId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Is  Required!.
        /// </summary>
        internal static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Businesses to chat!.
        /// </summary>
        internal static string Message_NoBusinessOwnersToChat {
            get {
                return ResourceManager.GetString("Message_NoBusinessOwnersToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new conversation!.
        /// </summary>
        internal static string Message_StartANewConversation {
            get {
                return ResourceManager.GetString("Message_StartANewConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Is Required !.
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found!.
        /// </summary>
        internal static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification successfully created!.
        /// </summary>
        internal static string NotificationCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("NotificationCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification deleted successfully!.
        /// </summary>
        internal static string NotificationDeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("NotificationDeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification read successfully!.
        /// </summary>
        internal static string NotificationRead_SuccessMessage {
            get {
                return ResourceManager.GetString("NotificationRead_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification record not Found!.
        /// </summary>
        internal static string NotificationRecord_NotFound {
            get {
                return ResourceManager.GetString("NotificationRecord_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification unread successfully!.
        /// </summary>
        internal static string NotificationUnRead_SuccessMessage {
            get {
                return ResourceManager.GetString("NotificationUnRead_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification updated successfully!.
        /// </summary>
        internal static string NotificationUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("NotificationUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password doesn&apos;t match!.
        /// </summary>
        internal static string PasswordNotMatch_ErrorMessage {
            get {
                return ResourceManager.GetString("PasswordNotMatch_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Is Required!.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details created successfully!.
        /// </summary>
        internal static string PaymentDetailsCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("PaymentDetailsCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment details deleted successfully!.
        /// </summary>
        internal static string PaymentDetailsdeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("PaymentDetailsdeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paytm Id Is  Required.
        /// </summary>
        internal static string PaytmIdRequired {
            get {
                return ResourceManager.GetString("PaytmIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paytm Id Update successfully!.
        /// </summary>
        internal static string PaytmIdUpdate_SuccessMessage {
            get {
                return ResourceManager.GetString("PaytmIdUpdate_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number will not contain any empty/white space Required!.
        /// </summary>
        internal static string PhoneNumberNotEmptySpaceRequired {
            get {
                return ResourceManager.GetString("PhoneNumberNotEmptySpaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Is Required!.
        /// </summary>
        internal static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not updated! Something went wrong..
        /// </summary>
        internal static string ProfileNotUpdated_ErrorMessage {
            get {
                return ResourceManager.GetString("ProfileNotUpdated_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfuly!.
        /// </summary>
        internal static string ProfileUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("ProfileUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Deleted Successfully!.
        /// </summary>
        internal static string QueryDeleted_SuccessMessage {
            get {
                return ResourceManager.GetString("QueryDeleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not get data. Try Again later!.
        /// </summary>
        internal static string QueryDoesNotGetData_ErrorMessage {
            get {
                return ResourceManager.GetString("QueryDoesNotGetData_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query added successfuly!.
        /// </summary>
        internal static string QueryInserted_SuccessMessage {
            get {
                return ResourceManager.GetString("QueryInserted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query not found!.
        /// </summary>
        internal static string QueryNotFound_ErrorMessage {
            get {
                return ResourceManager.GetString("QueryNotFound_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query updated successfully!.
        /// </summary>
        internal static string QueryUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("QueryUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Created successfuly!.
        /// </summary>
        internal static string RatingCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("RatingCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Dance Created successfuly!.
        /// </summary>
        internal static string RatingDanceCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("RatingDanceCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Description Is Required .
        /// </summary>
        internal static string RatingDescriptionRequired {
            get {
                return ResourceManager.GetString("RatingDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Is Required.
        /// </summary>
        internal static string RatingRequired {
            get {
                return ResourceManager.GetString("RatingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Review Is Required.
        /// </summary>
        internal static string RatingReviewRequired {
            get {
                return ResourceManager.GetString("RatingReviewRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is Required.
        /// </summary>
        internal static string ReasonRequired {
            get {
                return ResourceManager.GetString("ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from Favourites!.
        /// </summary>
        internal static string RemovedFavourites_ErrorMessage {
            get {
                return ResourceManager.GetString("RemovedFavourites_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollowed successfully!.
        /// </summary>
        internal static string RemovedFollower_SuccessMessage {
            get {
                return ResourceManager.GetString("RemovedFollower_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove this user from favourite list?.
        /// </summary>
        internal static string RemoveFavouriteBusiness {
            get {
                return ResourceManager.GetString("RemoveFavouriteBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Body Is Required.
        /// </summary>
        internal static string ReviewBodyRequired {
            get {
                return ResourceManager.GetString("ReviewBodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Keywords Required.
        /// </summary>
        internal static string SearchKeywordsRequired {
            get {
                return ResourceManager.GetString("SearchKeywordsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search-By value Required.
        /// </summary>
        internal static string SearchValueRequired {
            get {
                return ResourceManager.GetString("SearchValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bussiness Owner Is Required!.
        /// </summary>
        internal static string SelectBussinessOwnerRequired {
            get {
                return ResourceManager.GetString("SelectBussinessOwnerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is Required.
        /// </summary>
        internal static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Account not created! Something went wrong..
        /// </summary>
        internal static string StudentAccountNotCreated_ErrorMessage {
            get {
                return ResourceManager.GetString("StudentAccountNotCreated_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Registered successfully!.
        /// </summary>
        internal static string StudentRegistered_SuccessMessage {
            get {
                return ResourceManager.GetString("StudentRegistered_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurName Is Required.
        /// </summary>
        internal static string SurNameRequired {
            get {
                return ResourceManager.GetString("SurNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Is Required!.
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Business Required!.
        /// </summary>
        internal static string TransferBusinessRequired {
            get {
                return ResourceManager.GetString("TransferBusinessRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer City Is Required!.
        /// </summary>
        internal static string TransferCityRequired {
            get {
                return ResourceManager.GetString("TransferCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer date must be in Package Validity dates.
        /// </summary>
        internal static string TransferDateMustBeInPackageValidity_ErrorMesssgae {
            get {
                return ResourceManager.GetString("TransferDateMustBeInPackageValidity_ErrorMesssgae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Package Added successfuly!.
        /// </summary>
        internal static string TransferPackageAdded_SuccessMessage {
            get {
                return ResourceManager.GetString("TransferPackageAdded_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allready requested!.
        /// </summary>
        internal static string TransferPackageAllreadyRequestErrorMesssgae {
            get {
                return ResourceManager.GetString("TransferPackageAllreadyRequestErrorMesssgae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Package Status Updated successfuly!.
        /// </summary>
        internal static string TransferPackageStatusUpdate_SuccessMessage {
            get {
                return ResourceManager.GetString("TransferPackageStatusUpdate_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Package Required!.
        /// </summary>
        internal static string TransferPlanPackageRequired {
            get {
                return ResourceManager.GetString("TransferPlanPackageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Reason Is Required!.
        /// </summary>
        internal static string TransferReasonRequired {
            get {
                return ResourceManager.GetString("TransferReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Start-Date Is Required!.
        /// </summary>
        internal static string TransferStartDateRequired {
            get {
                return ResourceManager.GetString("TransferStartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer State Is Required!.
        /// </summary>
        internal static string TransferStateRequired {
            get {
                return ResourceManager.GetString("TransferStateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Student is Required!.
        /// </summary>
        internal static string TransferStudentRequired {
            get {
                return ResourceManager.GetString("TransferStudentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Type Is Required!.
        /// </summary>
        internal static string TransferTypeRequired {
            get {
                return ResourceManager.GetString("TransferTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPI Id created successfully!.
        /// </summary>
        internal static string UPIIdCreated_SuccessMessage {
            get {
                return ResourceManager.GetString("UPIIdCreated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPI Id  Is Required.
        /// </summary>
        internal static string UPIIdRequired {
            get {
                return ResourceManager.GetString("UPIIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPI Id update successfully!.
        /// </summary>
        internal static string UPIIdUpdated_SuccessMessage {
            get {
                return ResourceManager.GetString("UPIIdUpdated_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Image Thumbnail Image Is Required.
        /// </summary>
        internal static string UserImageThumbnailImageRequired {
            get {
                return ResourceManager.GetString("UserImageThumbnailImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Image Title Is Required.
        /// </summary>
        internal static string UserImageTitleRequired {
            get {
                return ResourceManager.GetString("UserImageTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted!.
        /// </summary>
        internal static string UserImage_Deleted_SuccessMessage {
            get {
                return ResourceManager.GetString("UserImage_Deleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image save successfully.
        /// </summary>
        internal static string UserImage_Saved_SuccessMessage {
            get {
                return ResourceManager.GetString("UserImage_Saved_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image update successfully.
        /// </summary>
        internal static string UserImage_Update_SuccessMessage {
            get {
                return ResourceManager.GetString("UserImage_Update_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, user not found!.
        /// </summary>
        internal static string UserNotFound_ErrorMessage {
            get {
                return ResourceManager.GetString("UserNotFound_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Video Link Is Required.
        /// </summary>
        internal static string UserVideoLinkRequired {
            get {
                return ResourceManager.GetString("UserVideoLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted!.
        /// </summary>
        internal static string UserVideos_Deleted_SuccessMessage {
            get {
                return ResourceManager.GetString("UserVideos_Deleted_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video save successfully.
        /// </summary>
        internal static string UserVideos_Saved_SuccessMessage {
            get {
                return ResourceManager.GetString("UserVideos_Saved_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video update successfully.
        /// </summary>
        internal static string UserVideos_Update_SuccessMessage {
            get {
                return ResourceManager.GetString("UserVideos_Update_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Video Thumbnail Image Is Required.
        /// </summary>
        internal static string UserVideoThumbnailImageRequired {
            get {
                return ResourceManager.GetString("UserVideoThumbnailImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Video Title Is Required.
        /// </summary>
        internal static string UserVideoTitleRequired {
            get {
                return ResourceManager.GetString("UserVideoTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Valid Email Required!.
        /// </summary>
        internal static string ValidEmailRequired {
            get {
                return ResourceManager.GetString("ValidEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid month!.
        /// </summary>
        internal static string ValidExpiryMonthRequired {
            get {
                return ResourceManager.GetString("ValidExpiryMonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid year!.
        /// </summary>
        internal static string ValidExpiryYearRequired {
            get {
                return ResourceManager.GetString("ValidExpiryYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size too large. Please select a smaller image. (upto 1MB).
        /// </summary>
        internal static string ValidFileSize_ErrorMessage {
            get {
                return ResourceManager.GetString("ValidFileSize_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image type. Please select a JPEG, PNG.
        /// </summary>
        internal static string ValidImageFileType_ErrorMessage {
            get {
                return ResourceManager.GetString("ValidImageFileType_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required a Valid Phone Number!.
        /// </summary>
        internal static string ValidPhoneNumberRequired {
            get {
                return ResourceManager.GetString("ValidPhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid YouTube Link Is Required.
        /// </summary>
        internal static string ValidYouTubeLinkRequired {
            get {
                return ResourceManager.GetString("ValidYouTubeLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedio Description Is Required.
        /// </summary>
        internal static string VedioDescriptionRequired {
            get {
                return ResourceManager.GetString("VedioDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
