// <auto-generated />
namespace MasterZoneMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_58 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_58));
        
        string IMigrationMetadata.Id
        {
            get { return "202309271054373_update_58"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
