// <auto-generated />
namespace MasterZoneMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _update_129 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_update_129));
        
        string IMigrationMetadata.Id
        {
            get { return "202407161041005__update_129"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
