// <auto-generated />
namespace MasterZoneMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_120 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_120));
        
        string IMigrationMetadata.Id
        {
            get { return "202406271240248_update_120"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
