// <auto-generated />
namespace MasterZoneMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_96 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_96));
        
        string IMigrationMetadata.Id
        {
            get { return "202402021212527_update_96"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
