// <auto-generated />
namespace MasterZoneMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _update_130 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_update_130));
        
        string IMigrationMetadata.Id
        {
            get { return "202407181207216__update_130"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
